config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the routes
  resources :categories, only: [:index, :new, :create, :show] do
    resources :deals, only: [:new, :create]
  end

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "splash#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_and_belongs_to_many :deals, dependent: :destroy, join_table: 'deals_categories', foreign_key: 'category_id',
                                  association_foreign_key: 'deal_id', uniq: true

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: true
  validates :icon, presence: true
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories, dependent: :destroy, join_table: 'deals_categories', foreign_key: 'deal_id',
                                       association_foreign_key: 'category_id', uniq: true

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :deals, foreign_key: 'author_id', dependent: :destroy
  has_many :categories, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # Permit the `name` parameter for sign up forms.
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @user = current_user
    @categories = @user.categories.includes(:deals)
  end

  def new
    @user = current_user
    @category = @user.categories.new
  end

  def create
    @user = current_user
    @category = @user.categories.new(category_params)
    if @category.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = current_user
    # The `includes` method is used to avoid the N+1 query problem.
    @category = @user.categories.includes(:deals).find(params[:id])
    @deals = @category.deals
    # order deals by most recent first
    @deals = @deals.order(created_at: :desc)
  end

  private

  def category_params
    params.require(:category)
      .permit(:name, :icon)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def new
    @deal = Deal.new
    @categories = Category.where(author: current_user)
  end

  def create
    @deal = current_user.deals.new(deals_params.except(:category_ids))
    @deal.author = current_user
    @categories = Category.where(id: deals_params[:category_ids])
    @categories.each do |category|
      @deal.categories << category
    end
    if @deal.save
      flash[:success] = 'Successfully added New Expenditure.'
      redirect_to category_path(Category.find_by(id: @categories.first.id))
    else
      flash.now[:error] = 'Error: Failed to Add new Expenditure!'
      render :new
    end
  end

  private

  def deals_params
    params.require(:deal).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    if user_signed_in?
      redirect_to categories_path
    else
      render :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/categories/index.html.erb
<!-- app/views/categories/index.html.erb -->

<div class="categories-container">
<h2>Categories</h2>

<% if @categories.empty? %>
<h3>There are no categories yet.</h3>
<% else %>
<% @categories.each do |category| %>
  <div class="category-card">
  <img src="<%= category.icon %>" />
    <h2><%= category.name %></h2>

    <!-- calculate total amount spent on this category -->
    <p>Total Spent: $<%= category.deals.sum(:amount) %></p>

    <!-- This is a link to the category's show page -->
    <%= link_to 'View', category_path(category) %>
  </div>
<% end %>
<% end %>


<!-- link to categories new path -->
<button class="add-category-button">
<%= link_to 'Add a new category', new_category_path, style: "color: white;" %>
</button>
</div>

app/views/categories/new.html.erb
<!-- app/views/categories/new.html.erb -->

<h1>New Category</h1>

<%= form_for(@category) do |f| %>
  <div>
    <%= f.label :name, 'Category Name' %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :icon, 'Category Icon' %>
    <%= f.text_field :icon %>
  </div>

  <div>
    <%= f.submit 'Create Category' %>
  </div>
<% end %>

<%= link_to 'Back to Home', root_path %>

app/views/categories/show.html.erb
<!-- app/views/categories/show.html.erb -->

<div class="transactions-container">
<h1><%= @category.name %> Category</h1>

<div>
  <strong>Category Name:</strong>
  <%= @category.name %>
</div>

<!-- calculate total amount spent on this category -->
<div>
  <strong>Total Spent:</strong>
  $<%= @category.deals.sum(:amount) %>
</div>

<h2>Deals in this Category:</h2>

<% if @category.deals.any? %>
  <ul>
    <% @deals.each do |deal| %>
      <li class="transaction-card">
        <strong>Deal Name:</strong> <%= deal.name %><br>
        <strong>Deal Amount:</strong> <%= deal.amount %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No deals in this category.</p>
<% end %>

<!-- Add a new transaction button -->
<button class="add-transaction-button">
  <%= link_to 'Add a new deal', new_category_deal_path(@category), style: "color: white;" %>
</button>

<%= link_to 'Back to Home', root_path %>
</div>

app/views/deals/new.html.erb
<!-- app/views/deals/new.html.erb -->

<h2>Add New Deal</h2>
  <%= form_with model: @deal, url: category_deals_path, class: 'mt-4' do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, autofocus: true, class: 'form-control', required: true %>
    </div>
    <div class="mb-3">
      <%= form.label :amount, class: 'form-label' %>
      <%= form.number_field :amount, autofocus: true, step: '0.01', class: 'form-control', required: true %>
    </div>

    <div class="checkbox">
    <%= form.label :categories %>
    <%= form.collection_check_boxes :category_ids, current_user.categories, :id, :name, include_hidden: false, required: true %>
  </div>

    <%= form.submit "Add Deal", class: "btn btn-primary" %>
  <% end %>

  <%= link_to 'Back to Category', category_path(@categories.find_by(id: params[:category_id])) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <nav>
    <%= link_to "Budget App", root_path, id: "budget-app" %>
    </button>
    <div id="navbarSupportedContent">
      <ul id="signin-up-menu">
      <% if user_signed_in? %>
        <li>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-warning mb-1" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    </div>
</nav>

    <% if notice %> <p class="alert alert-success"><%= notice %></p> <% end %>
    <% if alert %> <p class="alert alert-danger"><%= alert %></p> <% end %>

    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<!-- It is the Splash Screen with Name, Login and Signup -->

<!-- app/views/splash/index.html.erb -->
<!-- Wrap it around a div with class container, so that it appears in the middle of the Screen -->
<div class="container">
<h1 class="text-center" style="font-size: 30px;">Budget App</h1>
<div class="text-center buttons-container">
  <button class="button-login btn btn-primary"><a href="/users/sign_in" class="btn btn-primary" style="color: white;">LOG IN</a></button>
  <a href="/users/sign_up" class="btn btn-primary" style="color: #434b54;">SIGN UP</a>
</div>
</div>